version: '3.9'

services:
  app:
    build: .
    container_name: inference-api
    ports:
      - "8000:8000"
    expose:
      - "8000"
    restart: always

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
